version: '3'

services:
  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: homework
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: homework
    ports:
      - 5432:5432

  server:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
    restart: on-failure
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: homework
      POSTGRES_USER: homework
      POSTGRES_PASSWORD: homework
      PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - db
